name: flutter_timeline_v2
description: "Updated flutter timeline package"
version: 4.0.1
homepage: https://github.com/naseebnaushad/flutter_timeline_v2
repository: https://github.com/naseebnaushad/flutter_timeline_v2
license: MIT

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

#